apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-jcua
  namespace: sbaird-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:1f32abdd7cf68dd5792c7ca247965d6d8233276e445ce521297ca9b98f9fbd63
        name: my-go
        resources: {}
status: {}
